title: Michelle Ang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduated from NUS with a bachelor degree in Biomedical Engineering. 
  <br><br>
  Knowledge in analysing given problems in design projects. 
  <br><br>
  Process-driven with approved track record and like to work in a team to find solution to business problem. 
  <br><br>
  Currently, enrolled in Associate Data Analyst program to be skilled in analytics tools for effective analyses of data, in order to pivot into data analytics professionals.  
  <br><br>
  <a href="https://www.linkedin.com/in/michelleangxy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
