title: Michelle Ang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently, enrolled in Associate Data Analyst program to be skilled in analytics tools for effective analyses of data, in order to pivot into data analytics professionals.  
  <br><br>
  <a href="https://www.linkedin.com/in/michelleangxy/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal

