title: Michelle Ang # your name (or website title) here
logo: <img src="images/dashboard_project_1.JPG?raw=true"/> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Process-driven with approved track record and like to work in a team to find solution to business problem.
  <br><br>
  Enrolled in Associate Data Analyst program to be skilled in analytics tools for effective analyses of data.
  <br><br>
  <a href="https://www.linkedin.com/in/michelleangxy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
